// pt_lib — universal scene shader.
//
// A data-driven path tracer with NO hardcoded scene content. Everything it
// draws comes from the Babylon scene:
//
//   * geometry  — every traceable mesh's world-space triangles, packed into
//                 tAABBTexture / tTriangleTexture, traversed via a BVH
//   * materials — a tMaterialData float texture generated by scene ingestion,
//                 so a material property tweak does not recompile this shader
//   * lights    — a tLightData float texture built by scene ingestion, so a
//                 light property tweak does not recompile this shader
//
// The generated constants are injected by the composer as a "prelude", so the
// scene data is baked into the compiled shader and there are no uniform arrays
// to bind.
//
// It plugs into the shared pathtracing_default_main, which handles camera rays,
// progressive accumulation (previousBuffer) and edge detection. A scene shader
// must therefore provide: SetupScene(), CalculateRadiance(...), and the
// rayOrigin / rayDirection globals.

(function (root) {
	'use strict';

	var PT_LIB = (root.PT_LIB = root.PT_LIB || {});

	var SOURCE = `
#version 300 es

precision highp float;
precision highp int;
precision highp sampler2D;

// 1 / 2048 — geometry data textures are 2048 wide
#define INV_TEXTURE_WIDTH 0.00048828125
#ifndef PT_MAX_BOUNCES
#define PT_MAX_BOUNCES 4
#endif
#define PT_DEBUG_DEPTH_FAR 30.0
#define PT_LIGHT_MARKER_RADIUS 0.25

// Geometry (BVH nodes + triangle vertex data) from scene ingestion
uniform sampler2D tAABBTexture;
uniform sampler2D tTriangleTexture;

// Lights. Unlike materials, lights are NOT baked as constants: the adapter
// packs them into this float texture (one column per light, four rows) so a
// property tweak uploads new values instead of recompiling the shader.
uniform sampler2D tLightData;

// Runtime debug view: 0 = off, 1 = albedo, 2 = normals, 3 = direct light only, 4 = depth
uniform float uDebugMode;

// 1 = draw a small glowing marker at each light so it is visible in the render
uniform float uShowLights;

// Required by pathtracing_default_main
vec3 rayOrigin;
vec3 rayDirection;

// Common defines (PI, material enums, INFINITY...), common uniforms
// (uCameraMatrix, uResolution, ...) and the previousBuffer / blueNoiseTexture
// samplers.
#include<pathtracing_defines_and_uniforms>
#include<pathtracing_random>
#include<pathtracing_solve_quadratic>
#include<pathtracing_calc_fresnel>
#include<pathtracing_boundingbox_intersect>
#include<pathtracing_bvhTriangle_intersect>
#include<pathtracing_bvhDoubleSidedTriangle_intersect>

// Image-based lighting from scene.environmentTexture. Cube maps are sampled
// by world direction; equirectangular 2D textures are mapped spherically. When
// the scene has no environment texture this returns the flat ambient colour.
vec3 ptEnvironmentColor(vec3 dir, float lod)
{
#ifdef PT_ENV_CUBE
	return textureLod(tEnvironmentTexture, dir, lod).rgb * PT_ENV_INTENSITY;
#elif defined(PT_ENV_2D)
	vec2 envUV;
	envUV.x = atan(dir.x, dir.z) * ONE_OVER_TWO_PI + 0.5;
	envUV.y = acos(clamp(-dir.y, -1.0, 1.0)) * ONE_OVER_PI;
	return textureLod(tEnvironmentTexture, envUV, lod).rgb * PT_ENV_INTENSITY;
#else
	return PT_AMBIENT;
#endif
}

vec2 stackLevels[28];

// vec4 boxNodeData0 = (.x idTriangle, .yzw aabbMin)
// vec4 boxNodeData1 = (.x idRightChild, .yzw aabbMax)
void GetBoxNodeData(const in float i, inout vec4 boxNodeData0, inout vec4 boxNodeData1)
{
	float ix2 = i * 2.0;
	ivec2 uv0 = ivec2( mod(ix2 + 0.0, 2048.0), (ix2 + 0.0) * INV_TEXTURE_WIDTH );
	ivec2 uv1 = ivec2( mod(ix2 + 1.0, 2048.0), (ix2 + 1.0) * INV_TEXTURE_WIDTH );
	boxNodeData0 = texelFetch(tAABBTexture, uv0, 0);
	boxNodeData1 = texelFetch(tAABBTexture, uv1, 0);
}

// Nothing to set up per fragment: the scene lives in generated constants and
// the geometry textures. default_main requires the symbol to exist.
void SetupScene() { }

// Closest hit along a ray. outN is the interpolated geometric normal, outMat
// the material index, outOID an object id for edge detection. Returns INFINITY
// when nothing is hit.
float TraceClosest(vec3 ro, vec3 rd, out vec3 outN, out int outMat, out float outOID, out vec2 outUV, out vec3 outTangent, out float outHand)
{
	outN = vec3(0.0, 1.0, 0.0);
	outMat = 0;
	outOID = -1.0;
	outUV = vec2(-1.0);
	outTangent = vec3(1.0, 0.0, 0.0);
	outHand = 1.0;

	if (PT_TRIANGLE_COUNT < 0.5)
	{
		return INFINITY;
	}

	vec3 inverseDir = 1.0 / rd;

	vec4 currentBoxNodeData0, nodeAData0, nodeBData0, tmpNodeData0;
	vec4 currentBoxNodeData1, nodeAData1, nodeBData1, tmpNodeData1;
	vec4 vd0, vd1, vd2, vd3, vd4, vd5, vd6, vd7;
	ivec2 uv0, uv1, uv2, uv3, uv4, uv5, uv6, uv7;

	float hitT = INFINITY;
	bool triangleLookupNeeded = false;
	float triangleID = 0.0;
	float triangleU = 0.0;
	float triangleV = 0.0;

	float stackptr = 0.0;
	vec2 currentStackData, stackDataA, stackDataB, tmpStackData;
	float d, tu, tv, id;
	bool skip = false;

	GetBoxNodeData(stackptr, currentBoxNodeData0, currentBoxNodeData1);
	currentStackData = vec2(stackptr, BoundingBoxIntersect(currentBoxNodeData0.yzw, currentBoxNodeData1.yzw, ro, inverseDir));
	stackLevels[0] = currentStackData;
	skip = (currentStackData.y < hitT);

	while (true)
	{
		if (!skip)
		{
			if (--stackptr < 0.0)
			{
				break;
			}

			currentStackData = stackLevels[int(stackptr)];

			if (currentStackData.y >= hitT)
			{
				continue;
			}

			GetBoxNodeData(currentStackData.x, currentBoxNodeData0, currentBoxNodeData1);
		}
		skip = false;

		if (currentBoxNodeData0.x < 0.0) // inner node
		{
			GetBoxNodeData(currentStackData.x + 1.0, nodeAData0, nodeAData1);
			GetBoxNodeData(currentBoxNodeData1.x, nodeBData0, nodeBData1);
			stackDataA = vec2(currentStackData.x + 1.0, BoundingBoxIntersect(nodeAData0.yzw, nodeAData1.yzw, ro, inverseDir));
			stackDataB = vec2(currentBoxNodeData1.x, BoundingBoxIntersect(nodeBData0.yzw, nodeBData1.yzw, ro, inverseDir));

			if (stackDataB.y < stackDataA.y)
			{
				tmpStackData = stackDataB;
				stackDataB = stackDataA;
				stackDataA = tmpStackData;

				tmpNodeData0 = nodeBData0; tmpNodeData1 = nodeBData1;
				nodeBData0 = nodeAData0;   nodeBData1 = nodeAData1;
				nodeAData0 = tmpNodeData0; nodeAData1 = tmpNodeData1;
			}

			if (stackDataB.y < hitT)
			{
				currentStackData = stackDataB;
				currentBoxNodeData0 = nodeBData0;
				currentBoxNodeData1 = nodeBData1;
				skip = true;
			}
			if (stackDataA.y < hitT)
			{
				if (skip)
				{
					stackLevels[int(stackptr++)] = stackDataB;
				}
				currentStackData = stackDataA;
				currentBoxNodeData0 = nodeAData0;
				currentBoxNodeData1 = nodeAData1;
				skip = true;
			}

			continue;
		}

		// leaf: one triangle per node, 8 texels of vertex data
		id = 8.0 * currentBoxNodeData0.x;

		uv0 = ivec2( mod(id + 0.0, 2048.0), (id + 0.0) * INV_TEXTURE_WIDTH );
		uv1 = ivec2( mod(id + 1.0, 2048.0), (id + 1.0) * INV_TEXTURE_WIDTH );
		uv2 = ivec2( mod(id + 2.0, 2048.0), (id + 2.0) * INV_TEXTURE_WIDTH );

		vd0 = texelFetch(tTriangleTexture, uv0, 0);
		vd1 = texelFetch(tTriangleTexture, uv1, 0);
		vd2 = texelFetch(tTriangleTexture, uv2, 0);

		d = BVH_DoubleSidedTriangleIntersect(
			vec3(vd0.xyz), vec3(vd0.w, vd1.xy), vec3(vd1.zw, vd2.x),
			ro, rd, tu, tv);

		if (d < hitT)
		{
			hitT = d;
			triangleID = id;
			triangleU = tu;
			triangleV = tv;
			triangleLookupNeeded = true;
		}
	}

	if (triangleLookupNeeded)
	{
		uv0 = ivec2( mod(triangleID + 0.0, 2048.0), (triangleID + 0.0) * INV_TEXTURE_WIDTH );
		uv1 = ivec2( mod(triangleID + 1.0, 2048.0), (triangleID + 1.0) * INV_TEXTURE_WIDTH );
		uv2 = ivec2( mod(triangleID + 2.0, 2048.0), (triangleID + 2.0) * INV_TEXTURE_WIDTH );
		uv3 = ivec2( mod(triangleID + 3.0, 2048.0), (triangleID + 3.0) * INV_TEXTURE_WIDTH );
		uv4 = ivec2( mod(triangleID + 4.0, 2048.0), (triangleID + 4.0) * INV_TEXTURE_WIDTH );
		uv5 = ivec2( mod(triangleID + 5.0, 2048.0), (triangleID + 5.0) * INV_TEXTURE_WIDTH );
		uv6 = ivec2( mod(triangleID + 6.0, 2048.0), (triangleID + 6.0) * INV_TEXTURE_WIDTH );
		uv7 = ivec2( mod(triangleID + 7.0, 2048.0), (triangleID + 7.0) * INV_TEXTURE_WIDTH );

		vd0 = texelFetch(tTriangleTexture, uv0, 0);
		vd1 = texelFetch(tTriangleTexture, uv1, 0);
		vd2 = texelFetch(tTriangleTexture, uv2, 0);
		vd3 = texelFetch(tTriangleTexture, uv3, 0);
		vd4 = texelFetch(tTriangleTexture, uv4, 0);
		vd5 = texelFetch(tTriangleTexture, uv5, 0);
		vd6 = texelFetch(tTriangleTexture, uv6, 0);
		vd7 = texelFetch(tTriangleTexture, uv7, 0);

		float triangleW = 1.0 - triangleU - triangleV;
		vec3 n = normalize(
			triangleW * vec3(vd2.yzw) +
			triangleU * vec3(vd3.xyz) +
			triangleV * vec3(vd3.w, vd4.xy));

		outUV = triangleW * vec2(vd4.zw) + triangleU * vec2(vd5.xy) + triangleV * vec2(vd5.zw);
		outN = n;
		outMat = int(vd6.x + 0.5);
		outTangent = vd6.yzw;
		outHand = vd7.x < 0.0 ? -1.0 : 1.0;
		outOID = triangleID;
	}

	return hitT;
}

vec3 randomUnitVector()
{
	float z = rng() * 2.0 - 1.0;
	float a = rng() * TWO_PI;
	float r = sqrt(max(0.0, 1.0 - z * z));
	return vec3(r * cos(a), r * sin(a), z);
}

// Cosine-weighted direction above the surface normal (Lambert importance sampling).
vec3 cosineHemisphere(vec3 nl)
{
	float r1 = rng();
	float r2 = rng();
	float phi = TWO_PI * r1;
	float sinTheta = sqrt(r2);
	float cosTheta = sqrt(max(0.0, 1.0 - r2));
	vec3 dir = vec3(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta);

	vec3 up = abs(nl.y) < 0.999 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
	vec3 tangent = normalize(cross(up, nl));
	vec3 bitangent = cross(nl, tangent);

	return normalize(tangent * dir.x + bitangent * dir.y + nl * dir.z);
}

// Light records come from tLightData: row 0 = pos.xyz + type, row 1 =
// direction, row 2 = colour + power, row 3 = spot cone data.
vec4 ptLightPosType(int i) { return texelFetch(tLightData, ivec2(i, 0), 0); }
vec4 ptLightDirection(int i) { return texelFetch(tLightData, ivec2(i, 1), 0); }
vec4 ptLightColorPower(int i) { return texelFetch(tLightData, ivec2(i, 2), 0); }
vec4 ptLightExtra(int i) { return texelFetch(tLightData, ivec2(i, 3), 0); }

// ---- microfacet specular (GGX / Trowbridge-Reitz, Smith, Schlick) ---------
// Direct lighting used to be Lambert-only, so metals (metallic == 1) received
// no light-sampled illumination at all and looked dim unless the scene had an
// environment to reflect. The specular lobe below adds highlights from the
// analytic lights.
float ptD_GGX(float ndh, float alpha)
{
	float a2 = alpha * alpha;
	float d = ndh * ndh * (a2 - 1.0) + 1.0;
	return a2 / max(ONE_OVER_PI * d * d, 1e-7);
}

// Smith visibility with the Schlick-GGX approximation (k = alpha / 2).
float ptG_Smith(float ndv, float ndl, float alpha)
{
	float k = alpha * 0.5;
	float gv = ndv / max(ndv * (1.0 - k) + k, 1e-5);
	float gl = ndl / max(ndl * (1.0 - k) + k, 1e-5);
	return gv * gl;
}

vec3 ptF_Schlick(vec3 f0, float vdh)
{
	return f0 + (vec3(1.0) - f0) * pow(1.0 - vdh, 5.0);
}

// Full specular BRDF for one light sample: D * G * F / (4 * NdotL * NdotV).
// The caller multiplies by power * NdotL, which cancels the NdotL here.
vec3 ptSpecularBRDF(vec3 n, vec3 l, vec3 v, float ndl, float ndv, vec3 f0, float roughness)
{
	// Floor alpha so a near-mirror lobe stays finite: a punctual light sampled
	// against a delta lobe would otherwise spike D without bound. (M5 adds
	// proper outlier clamping.)
	float alpha = max(roughness * roughness, 0.0025);
	vec3 h = normalize(l + v);
	float ndh = max(dot(n, h), 0.0);
	float vdh = max(dot(v, h), 0.0);
	float d = ptD_GGX(ndh, alpha);
	float g = ptG_Smith(ndv, ndl, alpha);
	return (d * g / max(4.0 * ndl * ndv, 1e-5)) * ptF_Schlick(f0, vdh);
}

// Next-event estimation over the scene's analytic lights. wo points from the
// surface toward the viewer. Returns diffuse + specular.
vec3 directLighting(vec3 x, vec3 nl, vec3 wo, vec3 albedo, float metallic, float roughness)
{
	vec3 diffuseSum = vec3(0.0);
	vec3 specularSum = vec3(0.0);
	float ndv = max(dot(nl, wo), 1e-4);
	vec3 f0 = mix(vec3(0.04), albedo, metallic);
	vec3 shadowN;
	int shadowMat;
	float shadowOID;
	vec2 shadowUV;
	vec3 shadowTangent;
	float shadowHand;

	for (int i = 0; i < PT_LIGHT_COUNT; i++)
	{
		float type = ptLightPosType(i).w;
		vec3 L;
		vec3 power;
		float lightDistance = INFINITY;

		if (type < 0.5) // sphere / point: inverse-square falloff
		{
			vec3 toLight = ptLightPosType(i).xyz - x;
			float d2 = dot(toLight, toLight);
			if (d2 < 0.0001)
			{
				continue;
			}
			float d = sqrt(d2);
			L = toLight / d;
			lightDistance = d;
			power = ptLightColorPower(i).rgb * ptLightColorPower(i).w / d2;
		}
		else if (type < 1.5) // directional
		{
			L = normalize(-ptLightDirection(i).xyz);
			power = ptLightColorPower(i).rgb * ptLightColorPower(i).w;
		}
		else if (type < 2.5) // ambient: background only, handled elsewhere
		{
			continue;
		}
		else // spot: inverse-square inside a cone around its direction
		{
			vec3 toLight = ptLightPosType(i).xyz - x;
			float d2 = dot(toLight, toLight);
			if (d2 < 0.0001)
			{
				continue;
			}
			float d = sqrt(d2);
			L = toLight / d;
			lightDistance = d;
			power = ptLightColorPower(i).rgb * ptLightColorPower(i).w / d2;

			vec4 extra = ptLightExtra(i);
			vec3 spotDir = normalize(ptLightDirection(i).xyz);
			float cosAngle = dot(-L, spotDir);
			if (cosAngle < extra.x)
			{
				continue; // outside the cone
			}
			if (extra.y > -1.5)
			{
				power *= smoothstep(extra.x, extra.y, cosAngle); // inner-angle soft edge
			}
			if (extra.z > 0.0)
			{
				power *= pow(cosAngle, extra.z); // Babylon exponent falloff
			}
		}

		float shadowT = TraceClosest(x + nl * uEPS_intersect, L, shadowN, shadowMat, shadowOID, shadowUV, shadowTangent, shadowHand);
		if (shadowT < lightDistance - uEPS_intersect)
		{
			continue; // occluded
		}

		float ndl = max(dot(nl, L), 0.0);
		if (ndl <= 0.0)
		{
			continue;
		}
		diffuseSum += power * ndl;
		specularSum += power * ndl * ptSpecularBRDF(nl, L, wo, ndl, ndv, f0, roughness);
	}

	return diffuseSum * albedo * (1.0 - metallic) * ONE_OVER_PI + specularSum;
}

vec3 CalculateRadiance(out vec3 objectNormal, out vec3 objectColor, out float objectID, out float pixelSharpness)
{
	vec3 radiance = vec3(0.0);
	vec3 throughput = vec3(1.0);

	// Mip level used to sample the environment when a ray escapes. A rough
	// specular bounce reads a blurrier mip (prefiltered cube maps), giving
	// roughness-dependent reflections instead of a mirror image.
	float envLod = 0.0;

	objectNormal = vec3(0.0);
	objectColor = vec3(0.0);
	objectID = -INFINITY;
	pixelSharpness = 0.0;

	// ---- debug views (first hit only) -------------------------------
	// Skipped by the AOV pass, which must stay deterministic.
#ifndef PT_AOV_ONLY
	if (uDebugMode > 0.5)
	{
		vec3 dn;
		int dmat;
		float doid;
		vec2 duv;
		vec3 dtan;
		float dhand;
		float dt = TraceClosest(rayOrigin, rayDirection, dn, dmat, doid, duv, dtan, dhand);

		if (dt >= INFINITY)
		{
			return vec3(0.05, 0.05, 0.05);
		}

		if (dot(dn, rayDirection) > 0.0)
		{
			dn = -dn;
		}

		dmat = clamp(dmat, 0, PT_MATERIAL_COUNT - 1);
		vec3 dalbedo = ptSampleAlbedo(dmat, duv);

		if (uDebugMode < 1.5)
		{
			return dalbedo; // albedo
		}
		if (uDebugMode < 2.5)
		{
			return dn * 0.5 + 0.5; // normals
		}

		vec3 dx = rayOrigin + rayDirection * dt;
		float dmetallic = clamp(ptMatParams(dmat).x, 0.0, 1.0);
		float droughness = clamp(ptMatParams(dmat).y, 0.02, 1.0);

		if (uDebugMode < 3.5)
		{
			return directLighting(dx, dn, -rayDirection, dalbedo, dmetallic, droughness); // direct light only
		}

		// depth: near = white, far = black
		return vec3(1.0 - clamp(dt / PT_DEBUG_DEPTH_FAR, 0.0, 1.0));
	}
#endif

	for (int bounce = 0; bounce < PT_MAX_BOUNCES; bounce++)
	{
		vec3 n;
		int mat;
		float oid;
		vec2 hitUV;
		vec3 tangent;
		float hand;
		float t = TraceClosest(rayOrigin, rayDirection, n, mat, oid, hitUV, tangent, hand);

#ifndef PT_AOV_ONLY
		// Optional visible light markers: point lights are delta emitters and are
		// invisible in a path tracer, so draw a small glowing ball at each one.
		if (uShowLights > 0.5)
		{
			float markerT = INFINITY;
			vec3 markerColor = vec3(0.0);

			for (int li = 0; li < PT_LIGHT_COUNT; li++)
			{
				float markerType = ptLightPosType(li).w;
				if (markerType > 0.5 && markerType < 2.5)
				{
					continue; // only lights that live at a position (point / spot)
				}

				vec3 oc = rayOrigin - ptLightPosType(li).xyz;
				float qa = dot(rayDirection, rayDirection);
				float qb = 2.0 * dot(rayDirection, oc);
				float qc = dot(oc, oc) - PT_LIGHT_MARKER_RADIUS * PT_LIGHT_MARKER_RADIUS;
				float qt0, qt1;
				solveQuadratic(qa, qb, qc, qt0, qt1);
				float qtt = qt0 > uEPS_intersect ? qt0 : (qt1 > uEPS_intersect ? qt1 : INFINITY);

				if (qtt < markerT)
				{
					markerT = qtt;
					markerColor = ptLightColorPower(li).rgb * 4.0 + vec3(0.25);
				}
			}

			if (markerT < t)
			{
				radiance += throughput * markerColor;
				break;
			}
		}
#endif

		if (t >= INFINITY)
		{
			radiance += throughput * ptEnvironmentColor(rayDirection, envLod);
			break;
		}

		vec3 x = rayOrigin + rayDirection * t;
		vec3 geoN = n;
		if (dot(geoN, rayDirection) > 0.0)
		{
			geoN = -geoN; // shade the side the ray came from
		}

		mat = clamp(mat, 0, PT_MATERIAL_COUNT - 1);
		vec3 albedo = ptSampleAlbedo(mat, hitUV);
		float metallic = clamp(ptMatParams(mat).x, 0.0, 1.0);
		float roughness = clamp(ptMatParams(mat).y, 0.02, 1.0);
		float emissiveStrength = ptMatParams(mat).z;

		// metallic/roughness map overrides (Babylon: roughness = G, metallic = B;
		// either channel can be opted out per material)
		vec2 mr = ptSampleMetallicRoughness(mat, hitUV);
		if (mr.x >= 0.0) { metallic = clamp(mr.x, 0.0, 1.0); }
		if (mr.y >= 0.0) { roughness = clamp(mr.y, 0.02, 1.0); }

		// shading normal: the geometric normal, optionally perturbed by a bump map
		n = ptApplyBump(mat, geoN, tangent, hand, hitUV);

		if (bounce == 0)
		{
			objectNormal = n;
			objectColor = albedo;
			objectID = oid;
			// First-hit AOVs, read by the AOV pass (pathtracing_default_main
			// under PT_AOV_PASS).
			ptFirstHitAlbedo = albedo;
			ptFirstHitNormal = n;
			ptFirstHitDepth = t;
#ifdef PT_AOV_ONLY
			return radiance; // the AOV pass needs only the first hit
#endif
		}

		// Emission is added but does NOT terminate the path: that way a wrong
		// emissive flag can never blacken a surface (it just adds nothing).
		radiance += throughput * ptMatEmissive(mat).rgb * emissiveStrength * ptSampleEmissive(mat, hitUV);

		radiance += throughput * directLighting(x, n, -rayDirection, albedo, metallic, roughness);

		// choose the next bounce
		if (rng() < metallic)
		{
			vec3 reflection = reflect(rayDirection, n);
			rayDirection = normalize(reflection + roughness * roughness * randomUnitVector());
			throughput *= albedo;
			envLod = roughness * PT_ENV_MAX_LOD;
		}
		else
		{
			rayDirection = cosineHemisphere(n);
			throughput *= albedo * (1.0 - metallic);
			envLod = 0.0;
		}

		if (dot(rayDirection, n) < 0.0)
		{
			rayDirection = n;
		}

		rayOrigin = x + geoN * uEPS_intersect;
	}

	return radiance;
}

// Provides main(): camera ray generation, progressive accumulation and edge
// detection.
#include<pathtracing_default_main>
`;

	PT_LIB.defineSceneShader('universal', SOURCE);
})(typeof window !== 'undefined' ? window : globalThis);
