// Builds dist/pt_lib.core.js — the core of the library in load order.
//
// Concatenates, in order:
//   1. GLSL fragment shaders   (screenCopy, screenOutput)
//   2. GLSL includes           (pathtracing_* keys)
//   3. BVH builder             (SAH quality)
//
// Result is a single classic script to load after Babylon.js and before any
// scene script. Regenerate after editing anything in src/core/.
//
// Usage:  node pt_lib/tools/build-core.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, ".."); // pt_lib/
const glslRoot = path.join(root, "src", "core", "glsl");
const outDir = path.join(root, "dist");

fs.mkdirSync(outDir, { recursive: true });

const manifest = JSON.parse(
  fs.readFileSync(path.join(glslRoot, "MANIFEST.json"), "utf8")
);

const parts = [];

parts.push("// pt_lib core bundle — GENERATED by tools/build-core.mjs. Do not edit by hand.");
parts.push("// Contents: GLSL registry + fragment shaders + includes + BVH builder.");
parts.push("// Load order: after Babylon.js, before any scene script.");
parts.push("// Rebuild with: node pt_lib/tools/build-core.mjs");
parts.push("");

parts.push("// ================================================================");
parts.push("// GLSL registry (must load before the shader/include files below)");
parts.push("// ================================================================");
parts.push(fs.readFileSync(path.join(glslRoot, "_registry.js"), "utf8").trimEnd());
parts.push("");

for (const entry of manifest) {
  const filePath = path.join(root, entry.file);
  parts.push("// ================================================================");
  parts.push("// " + entry.store + " :: " + entry.name);
  parts.push("// ================================================================");
  parts.push(fs.readFileSync(filePath, "utf8").trimEnd());
  parts.push("");
}

const bvh = path.join(root, "src", "core", "bvh", "BVH_SAH_Quality_Builder.js");
parts.push("// ================================================================");
parts.push("// BVH builder :: BVH_SAH_Quality_Builder");
parts.push("// ================================================================");
parts.push(fs.readFileSync(bvh, "utf8").trimEnd());
parts.push("");

const outFile = path.join(outDir, "pt_lib.core.js");
fs.writeFileSync(outFile, parts.join("\n"), "utf8");

const bytes = fs.statSync(outFile).size;
console.log("Wrote " + outFile);
console.log("  sections: " + (manifest.length + 1));
console.log("  size:     " + bytes + " bytes");
