// Builds the publishable bundles from the classic-script sources.
//
//   dist/pt_lib.esm.js   ESM: imports @babylonjs/core (peer), re-exports the
//                        library. For bundlers / `import`.
//   dist/pt_lib.iife.js  classic script: expects a global BABYLON (script tag).
//
// The sources are classic IIFEs that attach to PT_LIB and read the global
// BABYLON, so bundling is concatenation plus a prologue, not transpilation.
// The geometry worker's two sources are inlined into the bundle as strings so
// the worker path keeps working without sibling files to importScripts.
//
// Run after tools/build-core.mjs (it consumes dist/pt_lib.core.js).
// Usage:  node pt_lib/tools/build-dist.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, ".."); // pt_lib/
const outDir = path.join(root, "dist");

// Evaluation order matters: the registry/shaders/BVH first, then the modules
// that register into PT_LIB, then the effect/class, then the scene shaders and
// adapters. Legacy hosts (the *_Path_Tracing.js files) are deliberately excluded.
const SOURCES = [
  "dist/pt_lib.core.js",
  "src/core/composer.js",
  "src/core/uniforms.js",
  "src/core/geometry-packing.js",
  "src/core/geometry-worker.js",
  "src/core/ingest.js",
  "src/denoise/oidn.js",
  "src/denoise/atrous.js",
  "src/PathTracer.js",
  "src/scenes/gltf/GLTFModelPathTracing_FragmentShader.js",
  "src/scenes/gltf/gltf-scene.js",
  "src/scenes/universal/UniversalPathTracing_FragmentShader.js",
  "src/scenes/universal/universal-scene.js",
  "src/scenes/gltf-hdri/HDRIEnvironmentPathTracing_FragmentShader.js",
  "src/scenes/physical-sky/PhysicalSkyModel_FragmentShader.js",
  "src/scenes/native/BabylonPathTracing_FragmentShader.js",
];

const WORKER_SOURCES = [
  "src/core/geometry-packing.js",
  "src/core/bvh/BVH_SAH_Quality_Builder.js",
];

const BANNER = [
  "// pt_lib — babylon-pathtracer — GENERATED by tools/build-dist.mjs.",
  "// Do not edit by hand; edit src/ and rebuild (`npm run build`).",
];

function readSource(rel) {
  const file = path.join(root, rel);
  if (!fs.existsSync(file)) {
    if (rel === "dist/pt_lib.core.js") {
      throw new Error(
        "dist/pt_lib.core.js is missing — run `node tools/build-core.mjs` first."
      );
    }
    throw new Error("Missing source: " + rel);
  }
  return fs.readFileSync(file, "utf8").trimEnd();
}

const body = SOURCES.map(
  (rel) =>
    "// ============================================================\n" +
    "// " + rel + "\n" +
    "// ============================================================\n" +
    readSource(rel)
).join("\n\n");

// Inline the worker's sources so a bundled build can still spawn the worker.
const glue = [
  "",
  "// ==== bundle glue: inline the worker sources (no sibling files to import) ====",
  "(function (global) {",
  "  var PT = global.PT_LIB;",
  "  if (PT && PT.geometryWorker && PT.geometryWorker.configure) {",
  "    PT.geometryWorker.configure({",
  "      packingSource: " + JSON.stringify(readSource(WORKER_SOURCES[0])) + ",",
  "      bvhSource: " + JSON.stringify(readSource(WORKER_SOURCES[1])),
  "    });",
  "  }",
  "})(typeof window !== 'undefined' ? window : globalThis);",
  "",
].join("\n");

const esm = [
  ...BANNER,
  "",
  "// ESM entry. @babylonjs/core is a peer dependency: the classic sources read",
  "// the `BABYLON` global, so it is copied onto a plain object before they run",
  "// (an ES module namespace is read-only, and the library attaches",
  "// BABYLON.PathTracer to it).",
  "import * as BABYLON_NS from '@babylonjs/core';",
  "",
  "const __ptGlobal = typeof window !== 'undefined' ? window : globalThis;",
  "if (typeof __ptGlobal.BABYLON === 'undefined') {",
  "  __ptGlobal.BABYLON = Object.assign({}, BABYLON_NS);",
  "}",
  "",
  body,
  glue,
  "// ---- exports ----",
  "export const PT_LIB = __ptGlobal.PT_LIB;",
  "export const PathTracer = __ptGlobal.PT_LIB.PathTracer;",
  "export const scenes = __ptGlobal.PT_LIB.scenes;",
  "export const denoise = __ptGlobal.PT_LIB.denoise;",
  "export const glsl = __ptGlobal.PT_LIB.glsl;",
  "export const ingestScene = __ptGlobal.PT_LIB.ingestScene;",
  "export const ingestSceneAsync = __ptGlobal.PT_LIB.ingestSceneAsync;",
  "export const buildScenePrelude = __ptGlobal.PT_LIB.buildScenePrelude;",
  "export default __ptGlobal.PT_LIB;",
  "",
].join("\n");

const iife = [
  ...BANNER,
  "",
  "// IIFE / classic-script entry. Load Babylon.js first; this reads the global",
  "// BABYLON and exposes window.PT_LIB (and BABYLON.PathTracer).",
  "(function (global) {",
  "  'use strict';",
  "  if (typeof BABYLON === 'undefined') {",
  "    throw new Error(",
  "      '[pt_lib] the IIFE build needs a global BABYLON — load babylon.js first,' +",
  "      ' or use dist/pt_lib.esm.js.'",
  "    );",
  "  }",
  body,
  glue,
  "})(typeof window !== 'undefined' ? window : globalThis);",
  "",
].join("\n");

fs.mkdirSync(outDir, { recursive: true });
const esmFile = path.join(outDir, "pt_lib.esm.js");
const iifeFile = path.join(outDir, "pt_lib.iife.js");
fs.writeFileSync(esmFile, esm, "utf8");
fs.writeFileSync(iifeFile, iife, "utf8");

console.log("Wrote " + esmFile + "  (" + fs.statSync(esmFile).size + " bytes)");
console.log("Wrote " + iifeFile + "  (" + fs.statSync(iifeFile).size + " bytes)");
console.log("  sources: " + SOURCES.length + " (+ worker sources inlined)");
